on:
  workflow_call:
    inputs:
      genv:
        description: 'The name of Github environment, which configures all environment variables and secrets'
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.genv }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add SSH private key to access ADO git repos
      shell: bash
      run: |
        echo ${{ secrets.sample_secret_1 }} > output
        cat output