on:
    workflow_call:
      inputs:
        genv:
          description: 'The name of Github environment, which configures all environment variables and secrets'
          required: true
          type: string
  
  jobs:
    test-secret:
        uses: amocha/reusable-workflows/.github/workflows/test.yml@main
        with:
             genv: ${{ inputs.genv }}
        secrets: inherit
  